site:
  name: PochomLab
  site: 'https://y-izutsu.github.io/'
  # site: 'https://pochomlab.com/'
  #site: 'http://localhost:4321'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId:

# Default SEO metadata
metadata:
  title:
    default: PochomLab
    template: '%s — PochomLab'
  description: "生成AIと絵書制作を軸に、創作・技術・IP戦略を実装し、未来へ接続するラボ。"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: PochomLab
    images:
      - url: '~/assets/images/pochomlab-default.jpg'
        width: 1200
        height: 630
    type: website
  twitter:
    handle:
    site:
    cardType: summary_large_image

i18n:
  language: ja
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: false
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: false

    category:
      isEnabled: false
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: false

    tag:
      isEnabled: false
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 0

analytics:
  vendors:
    googleAnalytics:
      id: G-5G55TKSD16 #G-WD89FTQ757

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
